import { StyleSheet, StatusBar, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1E1E2C',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight + 10,
    paddingBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: '#252636',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 0,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#E5E5E9',
    letterSpacing: 1,
  },
  headerActionButtons: {
    flexDirection: 'row',
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: 'rgba(174, 99, 228, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    borderWidth: 1,
    borderColor: 'rgba(174, 99, 228, 0.3)',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 25,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#E5E5E9',
  },
  seeAllButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#32323E',
  },
  seeAllText: {
    color: '#AE63E4',
    fontSize: 14,
    fontWeight: '600',
  },
  quickOptionsSection: {
    paddingLeft: 0,
    marginTop: 5,
  },
  friendGroupsSection: {
    marginTop: 10,
  },
  meetingsSection: {
    marginTop: 20,
    marginBottom: 80,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#252636',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#2C2C3E',
    paddingBottom: 10,
    paddingTop: 10,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    marginBottom: 4,
  },
  tabLabel: {
    fontSize: 12,
    color: '#9797A9',
  },
  activeTabLabel: {
    color: '#AE63E4',
  },
  
  // Arama modalı stilleri
  modalContainer: {
    flex: 1,
    backgroundColor: '#1E1E2C',
    width: '100%',
    height: '100%',
  },
  modalContent: {
    flex: 1,
    backgroundColor: '#1E1E2C',
    width: '100%',
    height: '100%',
    padding: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight + 10,
  },
  searchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#32323E',
  },
  searchTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E5E5E9',
  },
  searchInputContainer: {
    flexDirection: 'row',
    backgroundColor: '#32323E',
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    alignItems: 'center',
    paddingRight: 10,
  },
  searchInput: {
    flex: 1,
    color: '#E5E5E9',
    paddingVertical: 15,
    paddingHorizontal: 10,
    fontSize: 16,
    height: 55,
  },
  searchButton: {
    backgroundColor: '#AE63E4',
    width: 55,
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultsList: {
    flex: 1,
    marginTop: 10,
  },
  userCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    backgroundColor: '#32323E',
    borderRadius: 15,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  userAvatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: '#AE63E4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
  userName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E5E9',
  },
  addButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#AE63E4',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  friendActionButton: {
    flexDirection: 'row',
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: '#AE63E4',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  friendActionButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  statusText: {
    textAlign: 'center',
    color: '#9797A9',
    fontSize: 16,
    marginTop: 50,
  },
  // Bekleyen İstekler Stilleri
  pendingRequestsSection: {
    marginBottom: 20,
  },
  pendingRequestsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
  },
  pendingRequestsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pendingRequestsIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFAC30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  pendingRequestsTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  pendingRequestsSubtitle: {
    fontSize: 13,
    color: '#9797A9',
  },
});
