import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    marginHorizontal: 20,
    marginVertical: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E5E9',
  },
  headerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#32323E',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  headerButtonText: {
    color: '#AE63E4',
    marginRight: 6,
    fontWeight: '600',
    fontSize: 13,
  },
  groupsScrollContainer: {
    paddingRight: 20,
    paddingBottom: 10,
  },
  groupCard: {
    backgroundColor: '#252636',
    borderRadius: 16,
    width: 200,
    marginRight: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#32323E',
    borderLeftWidth: 3,
  },
  groupIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  groupName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(174, 99, 228, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 12,
    color: '#AE63E4',
    marginLeft: 5,
  },
  groupMembers: {
    fontSize: 13,
    color: '#9797A9',
  },
  groupDivider: {
    height: 1,
    backgroundColor: '#32323E',
    marginVertical: 12,
  },
  groupFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  avatarsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#252636',
    marginRight: -10,
  },
  moreAvatars: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#32323E',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  moreAvatarsText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  viewButton: {
    backgroundColor: '#32323E',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  viewButtonText: {
    fontSize: 12,
    color: '#E5E5E9',
    fontWeight: '600',
  },
  createGroupCard: {
    backgroundColor: 'rgba(174, 99, 228, 0.15)',
    borderRadius: 16,
    width: 140,
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(174, 99, 228, 0.3)',
    borderStyle: 'dashed',
  },
  createGroupIcon: {
    backgroundColor: 'rgba(174, 99, 228, 0.7)',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  plusBadge: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    right: -5,
    bottom: -5,
    borderWidth: 2,
    borderColor: '#AE63E4',
  },
  plusBadgeText: {
    color: '#AE63E4',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 16,
  },
  createGroupText: {
    color: '#AE63E4',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  // Boş durum göstergesi için stiller
  emptyStateCard: {
    backgroundColor: '#252636',
    borderRadius: 16,
    width: 250,
    marginRight: 16,
    padding: 24,
    borderColor: '#32323E',
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
    marginVertical: 10,
  },
  emptyStateText: {
    color: '#E5E5E9',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 12,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateSubText: {
    color: '#9797A9',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 10,
    lineHeight: 20,
  },
  notificationBadge: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    right: -5,
    top: -5,
    borderWidth: 2,
    borderColor: '#252636',
  },
  notificationText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
}); 