import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    marginHorizontal: 20,
    marginTop: 5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#E5E5E9',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#32323E',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  filterButtonText: {
    color: '#FFAC30',
    marginRight: 6,
    fontWeight: '600',
    fontSize: 13,
  },
  // Takvim Görünümü Stilleri
  calendarContainer: {
    marginBottom: 20,
    backgroundColor: '#252636',
    borderRadius: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  calendarScrollContent: {
    paddingHorizontal: 15,
  },
  dateItem: {
    alignItems: 'center',
    marginHorizontal: 8,
    width: 40,
  },
  selectedDateItem: {
    transform: [{scale: 1.05}],
  },
  weekDay: {
    fontSize: 12,
    color: '#9797A9',
    marginBottom: 8,
    fontWeight: '500',
  },
  selectedWeekDay: {
    color: '#FFAC30',
    fontWeight: 'bold',
  },
  dateCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#32323E',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  selectedDateCircle: {
    backgroundColor: '#FFAC30',
  },
  todayCircle: {
    borderWidth: 2,
    borderColor: '#FFAC30',
  },
  dateNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  selectedDateNumber: {
    color: '#252636',
  },
  eventDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFAC30',
  },
  // Etkinlik Kartları Stilleri
  eventsScrollContainer: {
    paddingRight: 20,
    paddingBottom: 10,
  },
  eventCard: {
    backgroundColor: '#252636',
    borderRadius: 16,
    width: 200,
    marginRight: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#32323E',
  },
  eventDateBadge: {
    backgroundColor: '#FFAC30',
    borderRadius: 8,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  eventDay: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  eventMonth: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    marginTop: -2,
  },
  eventTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  eventTime: {
    color: '#FFAC30',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  eventLocation: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventLocationText: {
    color: '#9797A9',
    fontSize: 13,
    marginLeft: 4,
    flex: 1,
  },
  eventDivider: {
    height: 1,
    backgroundColor: '#32323E',
    marginVertical: 12,
  },
  eventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  avatarsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  participantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#252636',
    marginRight: -10,
  },
  moreParticipants: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#32323E',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  moreParticipantsText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  joinButton: {
    backgroundColor: '#FFAC30',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  joinButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  createEventCard: {
    backgroundColor: 'rgba(255, 172, 48, 0.15)',
    borderRadius: 16,
    width: 150,
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 172, 48, 0.3)',
    borderStyle: 'dashed',
  },
  createEventIcon: {
    backgroundColor: 'rgba(255, 172, 48, 0.7)',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  plusBadge: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    right: -5,
    bottom: -5,
    borderWidth: 2,
    borderColor: '#FFAC30',
    zIndex: 10,
  },
  plusBadgeText: {
    color: '#FFAC30',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 16,
  },
  createEventText: {
    color: '#FFAC30',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  
  // Boş Buluşmalar Durumu
  emptyMeetingsContainer: {
    backgroundColor: '#252636',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: width - 160,
    marginLeft: 16,
    height: 200,
    marginVertical: 10,
  },
  emptyMeetingsText: {
    color: '#E5E5E9',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 12,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyMeetingsSubText: {
    color: '#9797A9',
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 10,
    lineHeight: 20,
  },
  
  // Yeni Buluşma Modalı
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#252636',
    width: '90%',
    height: '80%',
    borderRadius: 20,
    padding: 20,
    paddingBottom: 80,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#E5E5E9',
  },
  formContainer: {
    paddingBottom: 80,
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    color: '#E5E5E9',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 16,
  },
  formHint: {
    color: '#9797A9',
    fontSize: 12,
    marginTop: 4,
    fontStyle: 'italic',
  },
  formInfo: {
    backgroundColor: 'rgba(255, 172, 48, 0.1)',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    color: '#FFAC30',
    fontSize: 13,
    lineHeight: 18,
  },
  datePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  datePickerItem: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 10,
    marginRight: 10,
  },
  datePickerItemSelected: {
    backgroundColor: 'rgba(255, 172, 48, 0.2)',
    borderWidth: 1,
    borderColor: '#FFAC30',
  },
  datePickerText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  datePickerTextSelected: {
    color: '#FFAC30',
    fontWeight: 'bold',
  },
  friendsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  friendItem: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 10,
    marginRight: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    width: '47%',
  },
  friendItemSelected: {
    backgroundColor: 'rgba(255, 172, 48, 0.2)',
    borderWidth: 1,
    borderColor: '#FFAC30',
  },
  friendAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  friendAvatarPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFAC30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  friendAvatarText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  friendName: {
    color: '#FFFFFF',
    fontSize: 14,
    flex: 1,
  },
  friendSelectedIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFAC30',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButton: {
    backgroundColor: '#FFAC30',
    borderRadius: 12,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  noFriendsText: {
    color: '#9797A9',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 10,
  },
  
  // Geliştirilmiş takvim için yeni stiller
  datePickerButton: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  datePickerButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  calendarWrapper: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  calendarTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  weekDaysHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  weekDayText: {
    color: '#9797A9',
    fontSize: 14,
    width: 30,
    textAlign: 'center',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  calendarDay: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  calendarDayDisabled: {
    opacity: 0.3,
  },
  calendarDayToday: {
    borderWidth: 1,
    borderColor: '#FFAC30',
  },
  calendarDaySelected: {
    backgroundColor: '#FFAC30',
  },
  calendarDayText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  calendarDayTextDisabled: {
    color: '#9797A9',
  },
  calendarDayTextToday: {
    fontWeight: 'bold',
  },
  calendarDayTextSelected: {
    color: '#252636',
    fontWeight: 'bold',
  },
  calendarEventDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FFAC30',
    bottom: 2,
  },
  
  // Geliştirilmiş katılımcı seçimi için yeni stiller
  selectedFriendsContainer: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 10,
    marginBottom: 15,
    minHeight: 50,
  },
  selectedFriendChip: {
    backgroundColor: 'rgba(255, 172, 48, 0.2)',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#FFAC30',
  },
  selectedFriendAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 8,
  },
  selectedFriendAvatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFAC30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  selectedFriendAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  selectedFriendName: {
    color: '#FFAC30',
    fontSize: 14,
    marginRight: 8,
    maxWidth: 100,
  },
  removeSelectedFriendButton: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noSelectedFriendsText: {
    color: '#9797A9',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 10,
  },
  friendsSelectionLabel: {
    color: '#E5E5E9',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  
  // Arkadaş arama ve liste için yeni stiller
  searchFriendContainer: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 45,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    position: 'relative',
  },
  searchFriendInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    height: '100%',
  },
  clearSearchButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  friendsListContainer: {
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 5,
    height: Math.min(height * 0.25, 200), // Ekran yüksekliğinin %25'i veya maksimum 200px
    marginBottom: 10,
  },
  friendsList: {
    width: '100%',
    height: '100%',
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    width: '100%',
  },
  friendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 15,
  },
  friendAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFAC30',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  friendAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  friendName: {
    color: '#FFFFFF',
    fontSize: 16,
    flex: 1,
  },
  noSearchResultsText: {
    color: '#9797A9',
    fontSize: 15,
    textAlign: 'center',
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 15,
  },
  spacer: {
    height: 40, // Geniş bir boşluk
  },
  // Saat girişi için stiller
  timeInputContainer: {
    flexDirection: 'row',
    backgroundColor: '#32323E',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeInputField: {
    backgroundColor: '#252636',
    borderRadius: 8,
    width: 60,
    padding: 10,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  timeInputSeparator: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    paddingHorizontal: 10,
  },
}); 